### ISSUE TITLE
Unclear how to get the generated version into each application's build with nx affected

### ISSUE THREAD

**Issue by mklueh** [TheUnderScorer/nx-semantic-release#34]
Hello,

I'm trying to understand how to use this plugin. Let's say I just want to show somewhere in my application what the current version is, then I need to pass the version information into each application's build.

My current setup is something like this:

```
      - name: Semantic Release
        run: nx nx affected --target=semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploying changed apps
         run: nx affected --target=build-and-deploy
            
```

How would that be possible? Is the version info stored somewhere in context of the app, or would I have to combine semantic release and build + deploy into one single script myself?
