### ISSUE TITLE
[BUG]: "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by pmutua** [TheUnderScorer/nx-semantic-release#37]
During the semantic-release process, the following error occurred: `RangeError: Maximum call stack size exceeded`. The semantic-release version being used is 19.0.3 and plugins "verifyConditions" from "@semantic-release/changelog", "@semantic-release/git", and "@semantic-release/github" were loaded successfully. The automated release was run from the "master" branch on the repository.

Git authentication was successfully verified, but no git tag version was found on the branch "master". The semantic-release process retrieved all commits as no previous release was found and found 101 commits since the last release. The step "analyzeCommits" of plugin "[Function: nx-semantic-release]" failed, leading to the overall failure of the semantic-release process.

The error message also includes a stack trace with detailed information about the cause of the error. This appears to be a recursion error. 

[https://github.com/TheUnderScorer/nx-semantic-release/blob/d10480222028891d3d36fa94cd4e3747f6ccbe6d/packages/nx-semantic-release/src/common/project.ts#L15-L57](https://github.com/TheUnderScorer/nx-semantic-release/blob/d10480222028891d3d36fa94cd4e3747f6ccbe6d/packages/nx-semantic-release/src/common/project.ts#L15-L57)

## Actual Result
The semantic-release process failed with the error "RangeError: Maximum call stack size exceeded".

I'm using the following:

- NX version - 15.3.3
- Node - v18.12.1

##  Additional Information

A stack trace with more detailed information about the cause of the error is included in the initial description.

```bash
[9:07:28 PM] [semantic-release] › ℹ Running semantic-release version 19.0.3
[9:07:28 PM] [semantic-release] › ✔ Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[9:07:28 PM] [semantic-release] › ✔ Loaded plugin "verifyConditions" from "@semantic-release/git"
[9:07:28 PM] [semantic-release] › ✔ Loaded plugin "verifyConditions" from "@semantic-release/github"
[9:07:29 PM] [semantic-release] › ✔ Loaded plugin "publish" from "@semantic-release/github"
[9:07:29 PM] [semantic-release] › ✔ Loaded plugin "addChannel" from "@semantic-release/github"
[9:07:29 PM] [semantic-release] › ✔ Loaded plugin "fail" from "@semantic-release/github"
[9:07:32 PM] [semantic-release] › ✔ Run automated release from branch master on repository https://github.com/org/testproject
[9:07:33 PM] [semantic-release] › ✔ Allowed to push to the Git repository
[9:07:33 PM] [semantic-release] › ℹ Start step "verifyConditions" of plugin "@semantic-release/changelog"
[9:07:33 PM] [semantic-release] › ✔ Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[9:07:33 PM] [semantic-release] › ℹ Start step "verifyConditions" of plugin "@semantic-release/git"
[9:07:33 PM] [semantic-release] › ✔ Completed step "verifyConditions" of plugin "@semantic-release/git"
[9:07:33 PM] [semantic-release] › ℹ Start step "verifyConditions" of plugin "@semantic-release/github"
[9:07:33 PM] [semantic-release] [@semantic-release/github] › ℹ Verify GitHub authentication (https://api.github.com/)
[9:07:33 PM] [semantic-release] › ✔ Completed step "verifyConditions" of plugin "@semantic-release/github"
[9:07:33 PM] [semantic-release] › ℹ No git tag version found on branch master
[9:07:33 PM] [semantic-release] › ℹ No previous release found, retrieving all commits
[9:07:33 PM] [semantic-release] › ℹ Found 101 commits since last release
[9:07:33 PM] [semantic-release] › ℹ Start step "analyzeCommits" of plugin "[Function: nx-semantic-release]"
[9:07:33 PM] [semantic-release] › ✖ Failed step "analyzeCommits" of plugin "[Function: nx-semantic-release]"
[9:07:33 PM] [semantic-release] › ✖ An error occurred

[9:08:33 PM] [semantic-release] › ✖  An error occurred while running semantic-release: RangeError: Maximum call stack size exceeded
    at Function.from (<anonymous>)
    at Object.purry (/home/runner/work/testProject/testProject/node_modules/remeda/dist/commonjs/purry.js:43:27)
    at filter (/home/runner/work/testProject/testProject/node_modules/remeda/dist/commonjs/filter.js:8:20)
    at getRecursiveDependencies (/home/runner/work/testProject/testProject/node_modules/@theunderscorer/nx-semantic-release/src/common/project.js:[31](https://github.com/org/testProject/actions/runs/4162311067/jobs/7201326903#step:5:32):57)
    at /home/runner/work/testProject/testProject/node_modules/@theunderscorer/nx-semantic-release/src/common/project.js:[32](https://github.com/testProject/testProject/actions/runs/4162311067/jobs/7201326903#step:5:33):65
    at Array.reduce (<anonymous>)
    at /home/runner/work/testProject/testProject/node_modules/@theunderscorer/nx-semantic-release/src/common/project.js:31:199
    at pipe (/home/runner/work/testProject/testProject/node_modules/remeda/dist/commonjs/pipe.js:27:19)
    at getRecursiveDependencies (/home/runner/work/testProject/testProject/node_modules/@theunderscorer/nx-semantic-release/src/common/project.js:31:30)
    at /home/runner/work/testProject/testProject/node_modules/@theunderscorer/nx-semantic-release/src/common/project.js:32:65 {
  pluginName: '[Function: nx-semantic-release]'
}

 >  NX   Maximum call stack size exceeded

```

### Added the following workflow to test this:

```yaml

name: Auto Release Version

on:
  push:
    branches:
      - 'master'

permissions:
  checks: write
  pull-requests: write
  issues: write
  contents: write


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git User
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Install npm dependencies
        run:  yarn install --frozen-lockfile --non-interactive --no-progress --prefer-offline


      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx run testApp:semantic-release
```
