### ISSUE TITLE
Can't publish two affected libraries at the same time

### ISSUE THREAD

**Issue by tomavic** [TheUnderScorer/nx-semantic-release#60]
Hi there ✋ 

I've successfully installed your package inside my nx monorepo which contains two  simple libs and one app. 

I am using github actions to deploy the libs with `affected` command.

I ran into an error when the affected command tried to publish both libraries, 

Full log from here https://github.com/tomavic/enigma-nx-angular/actions/runs/4726308148/jobs/8385752785

Any ideas on how to solve this? As this contradict with the concept of having multi packages and the possibility of publishing multi package at the time is present when you have a larger project with many teams working on the same repo.

**Comment by Weetbix** [comment]
@tomavic I think by [default affected runs in parallel](https://nx.dev/packages/nx/documents/affected#parallel), you should pass `--parallel=false` 

I'm having success with:
`npx nx run-many --target=semantic-release --parallel=false`

Also I'm not sure you need to use `affected` itself, as this package runs affected internally, although i guess it doesnt hurt :)

**Comment by tomavic** [comment]
Thanks @Weetbix , What would you recommend instead of using `npx nx affected -t deploy` in my `ci.yml` ? 

```
      - name: Release 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx nx affected -t deploy
```
