### ISSUE TITLE
Assets are not uploading during release

### ISSUE THREAD

**Issue by Bogusik** [TheUnderScorer/nx-semantic-release#73]
I am having trouble trying to attach built files to the release assets. They are just not present in created GitHub Release.
I get no issues with creating git tags and changelog commits with version bumps.

My project has only one package called `frontend`

My config files:

```JSON5
// apps/frontend/project.json
{
  "name": "frontend",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "targets": {
    "semantic-release": {
      "executor": "@theunderscorer/nx-semantic-release:semantic-release",
      "options": {
        "github": true,
        "changelog": true,
        "npm": true,
        "git": true,
        "buildTarget": "build",
        "tagFormat": "frontend-v${VERSION}",
        "gitAssets": ["${PROJECT_DIR}/package.json"]
      }
    }
  }
}
```

```JSON5
// apps/frontend/package.json
{
  "name": "frontend",
  "version": "1.0.15",
  "private": true,
  "scripts": {
    "build": "vite build",
  },
  "dependencies": {
    "pinia": "^2.1.4",
    "vue": "^3.3.4",
    "vue-router": "^4.2.4"
  },
  "devDependencies": {
    "@rushstack/eslint-patch": "^1.3.2",
    "@types/jsdom": "^21.1.1",
    "@types/node": "^18.17.0",
    "@vitejs/plugin-vue": "^4.2.3",
    "@vue/test-utils": "^2.4.1",
    "@vue/tsconfig": "^0.4.0",
    "eslint-plugin-vue": "^9.15.1",
    "jsdom": "^22.1.0",
    "sass": "^1.64.2",
    "vite-plugin-zip": "^1.0.1",
    "vue-tsc": "^1.8.6"
  }
}
```

```JSON5
// .nxreleaserc.json
{
  "changelog": true,
  "npm": false,
  "github": true,
  "repositoryUrl": "<private_link>",
  "branches": ["main"],
  "commitMessage": "chore(release): ${nextRelease.version}",
  "git": true
}
```

```YAML
name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.5
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run: npx nx run-many --target=semantic-release --parallel=false --configuration=ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
